# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
n =np.zeros(10) 
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
z= np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [4]:
print(z.shape)

(39,)


5. Print the type of the previous array in question 3

In [5]:
print(z.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
np.__config__.show()

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [7]:
print(z.ndim)

1


8. Create a boolean array with all the True values

In [8]:
x = np.array([2,9,56,3,5], dtype = 'bool')
print(x)

[ True  True  True  True  True]


9. Create a two dimensional array




In [9]:
arr2 =np.array([[33,454,66,66],[3,4,5,6]])
print(arr2)

[[ 33 454  66  66]
 [  3   4   5   6]]


10. Create a three dimensional array



In [10]:
arr3 = np.array([[[3,44,55],[44,55,66]],[[56,57,58],[98,99,100]]])
print(arr3)

[[[  3  44  55]
  [ 44  55  66]]

 [[ 56  57  58]
  [ 98  99 100]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
z = np.arange(20,40)
z =z[::-1]
print(z)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
n = np.zeros(10)
n[5]= 1
print(n)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
idd = np.eye(3)
print(idd)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5])
arr = arr.astype("float")
print(arr.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
z = arr1*arr2
print(z)
    

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
comp = arr1 == arr2
eq_arr = comp.all()
print(eq_arr)

False


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(0,9)
a=arr[arr%2 == 1]
print(a)

[1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [18]:
arr[a] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
#arr[[5:7],8:12]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
z = np.ones((5,5))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array ([[1,2,3], [4,5,6],[7,8,9]])
arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0,0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr1= np.arange(9).reshape(3,3)
x = arr1[0]
print(x)

[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr1 = np.arange(9).reshape(3,3)
x = arr1[1,1]
print(x)

4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr1 = np.arange(9)
arr1 = arr1.reshape((3,3))
z = arr1[0:2,2:3]

print(z)

[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
x = np.random.randn(10,10)
print(x)
print('minimum value is', x.min())
print("maximum value is" ,x.max())

[[ 1.60643288e-02  8.30986132e-01  1.09335229e+00  2.54591308e+00
   6.37084885e-01 -1.01181078e+00  1.27313883e+00  1.71637449e+00
   1.25674590e+00 -7.43727666e-02]
 [ 2.06931523e-02  7.61318319e-01 -1.74428650e+00 -1.18791163e-01
   9.97315093e-01 -8.17454936e-01 -9.32034445e-01 -5.02761583e-01
   6.39792955e-02 -4.01649872e-01]
 [-1.29189228e-01 -1.49708856e-01 -1.20668448e-01 -9.32175559e-01
   9.90420716e-01  1.07697563e+00 -7.90222054e-01 -9.51184414e-01
  -9.79652298e-02  1.58187052e-01]
 [ 5.70291528e-01 -3.37462050e-01 -7.59957948e-01  7.83706733e-01
   6.77628640e-02 -4.26841220e-01 -4.93483242e-01 -1.43859841e+00
   2.00656863e+00  6.91520908e-01]
 [ 4.33621605e-01  8.00427767e-01  6.18534181e-01  7.70752564e-02
   6.11213782e-01 -1.21691169e+00  4.92365324e-01 -1.18353677e+00
  -6.65904240e-01 -5.09323583e-01]
 [ 1.04275025e+00 -4.05269772e-04 -1.13166330e+00  6.93333042e-01
   7.59252782e-01  4.97832454e-01 -1.65503689e+00 -1.32813382e+00
   9.00589386e-02  1.47929008e+00

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
z = np.intersect1d(a,b)
print(z)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
f = np.where(np.in1d(a, b))

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

#Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
x =data[names !="Will"]
print(x)

[[ 1.83475711  0.94355282 -1.33432168  0.14219941]
 [ 0.42576159 -1.07985059 -1.00052022 -1.19497505]
 [-0.07421806  0.92833977 -0.26085226  1.8362488 ]
 [ 0.39317931  1.7419766   0.02087006 -0.33427847]
 [ 0.2595738   0.12854489 -0.02063241  1.11624735]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
m = (names != "Will") & (names != "Joe")
print(data[m])

[[-0.42405936  0.80161962 -1.82743233  1.14708917]
 [-0.19448395 -0.32585544  1.36596682 -0.57881065]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
x = np.arange(1,16).reshape(5,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
x = np.arange(1,17).reshape(2,2,4)
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [33]:
np.swapaxes(x,2,0)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

In [34]:
y = np.arange(10)
x = np.sqrt(y)
print(np.where(x < 0.5,0,x))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
a1 = np.random.randn(12)
a2 = np.random.randn(12)
a3 = np.maximum(a1,a1)
print(a3)

[ 1.17985376  1.95403084 -0.82634168  0.20243486 -1.0050602  -0.5412301
  0.83668893 -2.12690725 -0.07135773 -0.03485605 -0.33493486 -0.28888365]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x =np.unique(names)
np.sort(x)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
x =np.delete(b,[0,1,2,3,4])

print(x)

[]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]]) 


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z= np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
a1 = np.random.randn(20)
print(np.cumsum(a1))

[-0.8899235  -1.31991124 -2.2313465  -1.60595452 -0.54303355  0.55076522
  0.02616757 -0.53537547 -2.00399296 -4.06074234 -4.81483331 -4.9172348
 -5.47205734 -4.30917044 -3.46426629 -5.06881139 -7.24302307 -7.87883601
 -7.75129293 -6.1586622 ]
